version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 sync build/ s3://profile-check-website-v1 --delete

artifacts:
  files: '**/*'
  base-directory: build
